import { Room, TimeSlot } from '../types/room';
import { UserSession } from '../types/booking';

export const VKU_TIME_SLOTS: readonly TimeSlot[] = [
  {
    id: 'SLOT_1',
    label: 'Ca 1 (07:30 - 09:30)',
    startTime: '07:30',
    endTime: '09:30',
    session: 'MORNING',
  },
  {
    id: 'SLOT_2',
    label: 'Ca 2 (09:30 - 11:30)',
    startTime: '09:30',
    endTime: '11:30',
    session: 'MORNING',
  },
  {
    id: 'SLOT_3',
    label: 'Ca 3 (13:00 - 15:00)',
    startTime: '13:00',
    endTime: '15:00',
    session: 'AFTERNOON',
  },
  {
    id: 'SLOT_4',
    label: 'Ca 4 (15:00 - 17:00)',
    startTime: '15:00',
    endTime: '17:00',
    session: 'AFTERNOON',
  },
] as const;

export const DEFAULT_USER_SESSION: UserSession = {
  id: 'usr_vku_23it196',
  studentId: '23IT196',
  name: 'Đặng Long Nhật',
  email: 'nhatdl.23it@vku.udn.vn',
  major: 'Kỹ thuật Phần mềm (Software Engineering)',
  department: 'Khoa Công nghệ Thông tin & Truyền thông',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
};

export const VKU_ROOMS: readonly Room[] = [
  {
    id: 'room_v204',
    code: 'V.204',
    name: 'Phòng Thực Hành AI & Data Science',
    building: 'V',
    floor: 2,
    capacity: 16,
    amenities: ['High-spec PC', 'Projector', 'AC', 'Ethernet'],
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80',
    description: 'Trang bị dàn máy trạm đồ họa GPU cao cấp phục vụ nghiên cứu Deep Learning, huấn luyện mô hình thị giác máy tính và phân tích dữ liệu lớn.',
    rules: [
      'Không mang đồ ăn và nước ngọt có ga vào khu vực máy trạm.',
      'Đăng xuất toàn bộ tài khoản cá nhân trước khi hoàn trả phòng.',
      'Tắt máy tính và điều hòa sau khi kết thúc ca sử dụng.',
    ],
  },
  {
    id: 'room_v301',
    code: 'V.301',
    name: 'Phòng Lab IoT & Hệ Thống Nhúng',
    building: 'V',
    floor: 3,
    capacity: 12,
    amenities: ['High-spec PC', 'Projector', 'Whiteboard', 'AC', 'Ethernet'],
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian thử nghiệm các thiết bị phần cứng Arduino, Raspberry Pi, vi điều khiển ESP32 và cảm biến thông minh trong mạng lưới công nghiệp 4.0.',
    rules: [
      'Bảo quản các bo mạch và linh kiện tại đúng tủ lưu trữ.',
      'Sử dụng mỏ hàn và thiết bị đo điện tại bàn thao tác kỹ thuật có cách điện.',
    ],
  },
  {
    id: 'room_v405',
    code: 'V.405',
    name: 'Phòng Hội Thảo Khoa Học & Báo Cáo Chuyên Đề',
    building: 'V',
    floor: 4,
    capacity: 20,
    amenities: ['Projector', 'Whiteboard', 'AC', 'Microphone'],
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    description: 'Thiết kế theo chuẩn phòng hội nghị quốc tế với micro không dây và hệ thống âm thanh vòm dành cho báo cáo chuyên đề và bảo vệ đồ án môn học.',
    rules: [
      'Yêu cầu trang phục chỉnh tề khi bảo vệ chuyên đề.',
      'Thu gom micro và trả lại bàn điều khiển âm thanh sau ca học.',
    ],
  },
  {
    id: 'room_a102',
    code: 'A.102',
    name: 'Phòng Thảo Luận Nhóm & Báo Cáo Đồ Án',
    building: 'A',
    floor: 1,
    capacity: 8,
    amenities: ['Whiteboard', 'AC', 'Projector'],
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian mở năng động phục vụ sinh viên làm việc nhóm theo mô hình Scrum/Agile, thảo luận sprint và trình chiếu tiến độ đồ án.',
    rules: [
      'Lau sạch bảng kính sau khi hoàn thành phiên thảo luận.',
      'Sắp xếp lại ghế theo vị trí ban đầu.',
    ],
  },
  {
    id: 'room_a205',
    code: 'A.205',
    name: 'Không Gian Tự Học Đa Chức Năng',
    building: 'A',
    floor: 2,
    capacity: 10,
    amenities: ['AC', 'Whiteboard', 'Ethernet'],
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80',
    description: 'Khu vực làm việc yên tĩnh với ổ cắm điện âm bàn tại từng vị trí, wifi băng thông cao phục vụ ôn thi kết thúc học phần và làm tiểu luận.',
    rules: [
      'Giữ trật tự chung, chuyển điện thoại sang chế độ rung.',
      'Không chiếm dụng chỗ ngồi khi rời khỏi phòng quá 20 phút.',
    ],
  },
  {
    id: 'room_a308',
    code: 'A.308',
    name: 'Phòng Lab Lập Trình Di Động & Cross-Platform',
    building: 'A',
    floor: 3,
    capacity: 14,
    amenities: ['High-spec PC', 'AC', 'Projector', 'Ethernet'],
    imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    description: 'Chuyên dụng cho môn Lập trình đa nền tảng React Native & Flutter, tích hợp máy trạm phục vụ build mã nguồn và kết nối cáp kiểm thử trực tiếp.',
    rules: [
      'Không tự ý gỡ hoặc thay đổi cấu hình máy ảo Android/iOS Emulator.',
      'Báo ngay cho cán bộ quản lý phòng nếu phát hiện cáp USB kết nối bị hỏng.',
    ],
  },
  {
    id: 'room_b101',
    code: 'B.101',
    name: 'Hội Trường Báo Cáo Tốt Nghiệp B101',
    building: 'B',
    floor: 1,
    capacity: 20,
    amenities: ['Projector', 'Microphone', 'AC', 'Whiteboard'],
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop&q=80',
    description: 'Hội trường báo cáo trang bị 2 màn chiếu cỡ lớn, hệ thống âm thanh giảng đường và bục thuyết trình tiêu chuẩn đại học.',
    rules: [
      'Cần có sự xác nhận của Giảng viên phụ trách môn học khi đặt phòng.',
      'Kiểm tra tình trạng máy chiếu trước và sau khi bàn giao ca.',
    ],
  },
  {
    id: 'room_b204',
    code: 'B.204',
    name: 'Phòng Học Trực Tuyến & Hội Nghị Từ Xa',
    building: 'B',
    floor: 2,
    capacity: 6,
    amenities: ['Projector', 'AC', 'High-spec PC', 'Microphone'],
    imageUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&auto=format&fit=crop&q=80',
    description: 'Buồng cách âm chuẩn Studio kèm Webcam 4K và micro lọc ồn thông minh, phục vụ phỏng vấn tuyển dụng trực tuyến và kết nối học giả quốc tế.',
    rules: [
      'Đóng kín cửa ra vào trong suốt buổi ghi âm hoặc họp trực tuyến.',
      'Không điều chỉnh hướng camera cố định.',
    ],
  },
  {
    id: 'room_b303',
    code: 'B.303',
    name: 'Phòng Nghiên Cứu Phần Mềm Khoa CNTT',
    building: 'B',
    floor: 3,
    capacity: 8,
    amenities: ['Whiteboard', 'AC', 'Ethernet'],
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian tập trung của các nhóm nghiên cứu sinh viên (Lab SE-VKU), chuẩn bị cho các cuộc thi Olympic Tin học và Lập trình sinh viên ICPC.',
    rules: [
      'Giữ gìn vệ sinh và không để sách tài liệu bừa bãi trên bàn làm việc.',
      'Bảo quản thiết bị mạng và cáp switch.',
    ],
  },
  {
    id: 'room_c201',
    code: 'C.201',
    name: 'Phòng Tự Học Nhóm Nhỏ Trung Tâm Học Liệu',
    building: 'C',
    floor: 2,
    capacity: 4,
    amenities: ['AC', 'Whiteboard'],
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&auto=format&fit=crop&q=80',
    description: 'Buồng tự học yên tĩnh tại tầng 2 Thư viện VKU dành riêng cho nhóm 2-4 sinh viên giải đề thi và làm bài tập nghiên cứu tài liệu.',
    rules: [
      'Nói chuyện thì thầm, không phát loa ngoài.',
      'Không mang sách chưa qua thủ tục mượn thư viện vào phòng.',
    ],
  },
  {
    id: 'room_c202',
    code: 'C.202',
    name: 'Phòng Đọc & Viết Báo Cáo Chuyên Sâu',
    building: 'C',
    floor: 2,
    capacity: 4,
    amenities: ['AC', 'Whiteboard', 'Ethernet'],
    imageUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian tối ưu ánh sáng tự nhiên cạnh cửa sổ kính hướng hồ nước khuôn viên VKU, truyền cảm hứng nghiên cứu khoa học sinh viên.',
    rules: [
      'Không tự ý kéo rèm che cửa sổ quá mạnh.',
      'Bảo vệ bề mặt bàn gỗ không vẽ viết bậy.',
    ],
  },
  {
    id: 'room_c305',
    code: 'C.305',
    name: 'Phòng Workshop & Ươm Mầm Khởi Nghiệp VKU',
    building: 'C',
    floor: 3,
    capacity: 16,
    amenities: ['Projector', 'Whiteboard', 'AC', 'Microphone'],
    imageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian thiết kế sáng tạo phục vụ các sự kiện Mini Hackathon, pitching dự án khởi nghiệp và giao lưu với cựu sinh viên doanh nghiệp.',
    rules: [
      'Đăng ký kế hoạch tổ chức sự kiện với Ban quản lý trước 24 giờ.',
      'Dọn dẹp rác và áp phích sau khi kết thúc buổi thuyết trình.',
    ],
  },
] as const;
